[package]
name = "base64ct-poc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
base64ct = { version = "1.0.0", features = ["alloc"] }
